import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Form from '../src/components/Form'
import Nav from '../src/components/Nav'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav />
        <Form />
      </main>

      
    </div>
  )
}
